export const CART_ITEM_ADD_REQUESTED = "CART_ITEM_ADD_REQUESTED";
export const CART_ITEM_ADDED_SUCCESSFULLY = "CART_ITEM_ADDED_SUCCESSFULLY";
export const CART_ITEM_ADD_FAILED = "CART_ITEM_ADD_FAILED";
export const CART_ITEM_REMOVED_SUCCESSFULLY = "CART_ITEM_REMOVED_SUCCESSFULLY";
export const CART_ITEM_QUANTITY_CHANGE_REQUESTED =
  "CART_ITEM_QUANTITY_CHANGE_REQUESTED";
export const CART_ITEM_QUANTITY_CHANGED = "CART_ITEM_QUANTITY_CHANGED";
export const CART_ITEM_QUANTITY_CHANGE_FAILED =
  "CART_ITEM_QUANTITY_CHANGE_FAILED";
