export const CHECKOUT_NEXT_STEP_REQUESTED = "CHECKOUT_NEXT_STEP_REQUESTED";
export const CHECKOUT_NEXT_STEP_REACHED = "CHECKOUT_NEXT_STEP_REACHED";
export const CHECKOUT_NEXT_STEP_FAILED = "CHECKOUT_NEXT_STEP_FAILED";
export const CHECKOUT_PREVIOUS_STEP_REQUESTED =
  "CHECKOUT_PREVIOUS_STEP_REQUESTED";
export const CHECKOUT_PREVIOUS_STEP_REACHED = "CHECKOUT_PREVIOUS_STEP_REACHED";
export const CHECKOUT_PREVIOUS_STEP_FAILED = "CHECKOUT_PREVIOUS_STEP_FAILED";
export const CHECKOUT_STEP_JUMP_REQUESTED = "CHECKOUT_STEP_JUMP_REQUESTED";
export const CHECKOUT_STEP_JUMP_COMPLETED = "CHECKOUT_STEP_JUMP_COMPLETED";
export const CHECKOUT_STEP_JUMP_FAILED = "CHECKOUT_STEP_JUMP_FAILED";
