export const EVENT_FETCH_REQUESTED = "EVENT_FETCH_REQUESTED";
export const EVENT_FETCHED_SUCCESSFULLY = "EVENT_FETCHED_SUCCESSFULLY";
export const EVENT_FETCH_HAS_FAILED = "EVENT_FETCH_HAS_FAILED";
export const EVENT_DELETE_REQUESTED = "EVENT_DELETE_REQUESTED";
export const EVENT_DELETED_SUCCESSFULLY = "EVENT_DELETED_SUCCESSFULLY";
export const EVENT_DELETE_HAS_FAILED = "EVENT_DELETE_HAS_FAILED";
export const SUBSCRIBED_EVENTS_FETCH_REQUESTED =
  "SUBSCRIBED_EVENTS_FETCH_REQUESTED";
export const SUBSCRIBED_EVENTS_FETCHED_SUCCESSFULLY =
  "SUBSCRIBED_EVENTS_FETCHED_SUCCESSFULLY";
export const SUBSCRIBED_EVENTS_FETCH_HAS_FAILED =
  "SUBSCRIBED_EVENTS_FETCH_HAS_FAILED";
export const EVENT_SELECT_REQUESTED = "EVENT_SELECT_REQUESTED";
export const EVENT_SELECTED_SUCCESSFULLY = "EVENT_SELECTED_SUCCESSFULLY";
export const EVENT_SELECT_FAILED = "EVENT_SELECT_FAILED";
