export const CREATE_NOTE_REQUESTED = "CREATE_NOTE_REQUESTED";
export const NOTE_CREATED_SUCCESSFULLY = "NOTE_CREATED_SUCCESSFULLY";
export const NOTE_CREATION_FAILED = "NOTE_CREATION_FAILED";
export const POST_NOTE_REQUESTED = "POST_NOTE_REQUESTED";
export const NOTE_POSTED_SUCCESSFULLY = "NOTE_POSTED_SUCCESSFULLY";
export const NOTE_POST_FAILED = "NOTE_POST_FAILED";
export const DELETED_NOTE_SUCCESFULLY = "DELETED_NOTE_SUCCESFULLY";
