export const CREATE_ORDER_REQUESTED = "CREATE_ORDER_REQUESTED";
export const ORDER_CREATED_SUCCESSFULLY = "ORDER_CREATED_SUCCESSFULLY";
export const ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED";
export const DELETED_ORDER_SUCCESFULLY = "DELETED_ORDER_SUCCESFULLY";
export const POST_ORDER_REQUESTED = "POST_ORDER_REQUESTED";
export const ORDER_POSTED_SUCCESFULLY = "ORDER_POSTED_SUCCESFULLY";
export const ORDER_POST_FAILED = "ORDER_POST_FAILED";
