export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGGED_IN_SUCCESSFULLY = "USER_LOGGED_IN_SUCCESSFULLY";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
